### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by brechtcs** [marijnh/mold#1]
Do you by any chance have some advice on which syntax highlighting scheme to use for Mold templates? There don't seem to be any dedicated ones (at least not for vim), and I can't find another templating language with a syntax that's similar enough to work.

**Comment by marijnh** [comment]
Not really. I use HTML mode when editing these.

**Comment by brechtcs** [comment]
Right, on my machine the `<<` and `>>` were being marked as syntax errors though, which was a bit annoying. For reference: I solved it by combining both answers to [this stackoverflow answer](https://stackoverflow.com/questions/10693207/how-can-i-disable-vims-html-error-highlighting), dropping the following in `~/.vim/after/syntax/html.vim`:

```vimscript
syntax region moldTag start="<<" end=">>" containedin=ALLBUT,moldTag
highlight default link moldTag Special
```
